# Generated by Django 5.2.1 on 2025-05-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='total_voters',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='poll_option',
            name='voter_n',
            field=models.BigIntegerField(default=0),
        ),
    ]
